server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"

  # data source configuration for connecting to the MySQL database
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root

  jpa:
    show-sql: true
    #this sql.init.mode property is used to initialize the database schema on application startup
    #it will read the schema.sql file and execute the SQL statements to create the necessary tables and structures in the database
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      access: unrestricted
  #to enable the info related properties
  info:
    evn:
      enabled: true

eureka:
  instance:
    #this will make the service register with its IP address instead of hostname
    preferIpAddress: true
  client:
    #when set to true, the service will register itself with the Eureka server upon startup
    fetchRegistry: true
    #this will register the service with the Eureka server so that it can be discovered by other services
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards Service"
    description: "Service for managing user cards by usman"
    version: "1.0.0"
